#!perl

# DATE
# VERSION

#use 5.010001;
use strict;
use warnings;

use Perinci::CmdLine::Any;
use Perinci::Sub::Gen::AccessTable qw(gen_read_table_func);

our %SPEC;

my $res = gen_read_table_func(
    name => 'app',
    summary => 'List Sah::Schemas::* modules',
    table_spec => {
        fields => {
            name => {
                schema => 'str*',
                pos => 0,
                sortable => 1,
            },
        },
        pk => 'name',
    },
    table_data => sub {
        require Module::List::Tiny;
        my $mods = Module::List::Tiny::list_modules(
            'Sah::Schemas::', {list_modules=>1, recurse=>1});
        my @rows;
        for my $mod (sort keys %$mods) {
            (my $name = $mod) =~ s/\ASah::Schemas:://;
            push @rows, {
                name => $name,
            };
        }
        {data => \@rows};
    },
);
die "Can't generate function: $res->[0] - $res->[1]" unless $res->[0] == 200;

Perinci::CmdLine::Any->new(
    url => '/main/app',
)->run;

# ABSTRACT:
# PODNAME:

=head1 SEE ALSO

L<list-sah-schema-modules>
