#!perl

# DATE
# VERSION

#use 5.010001;
use strict;
use warnings;

use Perinci::CmdLine::Any;
use Perinci::Sub::Gen::AccessTable qw(gen_read_table_func);
use Module::List::Tiny;

my $res = gen_read_table_func(
    name => 'app',
    summary => 'List Sah schema modules',
    table_data => sub {
        no strict 'refs';

        my $mods = Module::List::Tiny::list_modules(
            'Sah::Schema::', {list_modules=>1, recurse=>1});
        my @rows;
        for my $mod (sort keys %$mods) {
            $mod =~ /\ASah::Schema::(.+)/;
            my $row = {schema=>$1};
            (my $mod_pm = "$mod.pm") =~ s!::!/!g;
            require $mod_pm;
            my $sch = ${"$mod\::schema"};
            $row->{base} = $sch->[0];
            $row->{summary} = $sch->[1]{summary};
            push @rows, $row;
        }
        {data => \@rows};
    },
    table_spec => {
        fields => {
            schema => {
                schema => 'str*',
                pos => 0,
                sortable => 1,
            },
            base => {
                schema => 'str*',
                pos => 1,
                sortable => 1,
            },
        },
        pk => 'schema',
    },
);
die "Can't generate function: $res->[0] - $res->[1]" unless $res->[0] == 200;

Perinci::CmdLine::Any->new(url => '/main/app')->run;

# ABSTRACT:
# PODNAME:

=head1 SEE ALSO

L<show-sah-schema-module>

L<list-sah-schemas-modules>
