#!perl

use 5.010001;
use strict;
use warnings;

use Perinci::CmdLine::Any;

# AUTHORITY
# DATE
# DIST
# VERSION

our %SPEC;

$SPEC{resolve_sah_schema} = {
    v => 1.1,
    summary => 'Resolve Sah schema',
    args => {
        schema => {
            schema => 'str*', # XXX perl::data
            req => 1,
            pos => 0,
        },
        merge_clause_sets => {
            schema => 'bool*',
            default => 1,
        },
        allow_base_with_no_additional_clauses => {
            schema => 'bool*',
            default => 0,
        },
    },
};
sub resolve_sah_schema {
    require Data::Dump::Color;
    require Data::Sah::Resolve;

    my %args = @_;

    my $sch;
    if ($args{schema} =~ /\A\w+(::\w+)*\*?\z/) {
        $sch = $args{schema};
    } else {
        eval "\$sch = $args{schema}";
        die if $@;
    }

    my $nsch = Data::Sah::Resolve::resolve_schema(
        {
            merge_clause_sets        => $args{merge_clause_sets},
        },
        $sch);

    [200, "OK", Data::Dump::Color::dump($nsch) . "\n", {
        'cmdline.skip_format' => 1,
    }];
}

Perinci::CmdLine::Any->new(
    url => '/main/resolve_sah_schema',
)->run;

# ABSTRACT:
# PODNAME:

=head1 SYNOPSIS

 % resolve-sah-schema '"posint"'


=head1 DESCRIPTION

This script can be used to quickly produce/see the resolved form of a L<Sah>
schema. Both input and output are in the form of Perl code.


=head1 SEE ALSO

L<Data::Sah::Resolve>
